//----------------------------------------------------------------------------
/** @file HexPoints19x19.hpp */
//----------------------------------------------------------------------------

#ifndef HEXPOINT19x19_HPP
#define HEXPOINT19x19_HPP

/** A location on a Hex board.  A HexPoint's neighbours can be
    calculated only when considering what size board the point is in.
    See ConstBoard for an example board layout.

    @note The order of these points if very important. There are
    several pieces of code that rely on this ordering
    (StoneBoard::GetBoardID() is one of them). Change this only if you
    know what you are doing!
*/
typedef enum
{
    /** Dummy point. */
    INVALID_POINT = 0,

    /** Point used to denote a resign move by a player. 

        @todo since this is not really a point on a board, should we
        create a HexMove class and put this there? */
    RESIGN = 1,

    /** Point used to denote a swap move by a player. 

        @todo since this is not really a point on a board, should 
        we create a HexMove class and put this there?  */
    SWAP_PIECES = 2,

    /** The top edge. */
    NORTH = 3,

    /** The right edge. */
    EAST  = 4,

    /** The bottom edge. */
    SOUTH = 5,

    /** The left edge. */
    WEST  = 6,

    /** @name Interior cells. */
    // @{

    HEX_CELL_A1, HEX_CELL_B1, HEX_CELL_C1, HEX_CELL_D1, HEX_CELL_E1,
    HEX_CELL_F1, HEX_CELL_G1, HEX_CELL_H1, HEX_CELL_I1, HEX_CELL_J1,
    HEX_CELL_K1, HEX_CELL_L1, HEX_CELL_M1, HEX_CELL_N1, HEX_CELL_O1,
    HEX_CELL_P1, HEX_CELL_Q1, HEX_CELL_R1, HEX_CELL_S1,

    HEX_CELL_A2, HEX_CELL_B2, HEX_CELL_C2, HEX_CELL_D2, HEX_CELL_E2,
    HEX_CELL_F2, HEX_CELL_G2, HEX_CELL_H2, HEX_CELL_I2, HEX_CELL_J2,
    HEX_CELL_K2, HEX_CELL_L2, HEX_CELL_M2, HEX_CELL_N2, HEX_CELL_O2,
    HEX_CELL_P2, HEX_CELL_Q2, HEX_CELL_R2, HEX_CELL_S2,

    HEX_CELL_A3, HEX_CELL_B3, HEX_CELL_C3, HEX_CELL_D3, HEX_CELL_E3,
    HEX_CELL_F3, HEX_CELL_G3, HEX_CELL_H3, HEX_CELL_I3, HEX_CELL_J3,
    HEX_CELL_K3, HEX_CELL_L3, HEX_CELL_M3, HEX_CELL_N3, HEX_CELL_O3,
    HEX_CELL_P3, HEX_CELL_Q3, HEX_CELL_R3, HEX_CELL_S3,

    HEX_CELL_A4, HEX_CELL_B4, HEX_CELL_C4, HEX_CELL_D4, HEX_CELL_E4,
    HEX_CELL_F4, HEX_CELL_G4, HEX_CELL_H4, HEX_CELL_I4, HEX_CELL_J4,
    HEX_CELL_K4, HEX_CELL_L4, HEX_CELL_M4, HEX_CELL_N4, HEX_CELL_O4,
    HEX_CELL_P4, HEX_CELL_Q4, HEX_CELL_R4, HEX_CELL_S4,

    HEX_CELL_A5, HEX_CELL_B5, HEX_CELL_C5, HEX_CELL_D5, HEX_CELL_E5,
    HEX_CELL_F5, HEX_CELL_G5, HEX_CELL_H5, HEX_CELL_I5, HEX_CELL_J5,
    HEX_CELL_K5, HEX_CELL_L5, HEX_CELL_M5, HEX_CELL_N5, HEX_CELL_O5,
    HEX_CELL_P5, HEX_CELL_Q5, HEX_CELL_R5, HEX_CELL_S5,

    HEX_CELL_A6, HEX_CELL_B6, HEX_CELL_C6, HEX_CELL_D6, HEX_CELL_E6,
    HEX_CELL_F6, HEX_CELL_G6, HEX_CELL_H6, HEX_CELL_I6, HEX_CELL_J6,
    HEX_CELL_K6, HEX_CELL_L6, HEX_CELL_M6, HEX_CELL_N6, HEX_CELL_O6,
    HEX_CELL_P6, HEX_CELL_Q6, HEX_CELL_R6, HEX_CELL_S6,

    HEX_CELL_A7, HEX_CELL_B7, HEX_CELL_C7, HEX_CELL_D7, HEX_CELL_E7,
    HEX_CELL_F7, HEX_CELL_G7, HEX_CELL_H7, HEX_CELL_I7, HEX_CELL_J7,
    HEX_CELL_K7, HEX_CELL_L7, HEX_CELL_M7, HEX_CELL_N7, HEX_CELL_O7,
    HEX_CELL_P7, HEX_CELL_Q7, HEX_CELL_R7, HEX_CELL_S7,

    HEX_CELL_A8, HEX_CELL_B8, HEX_CELL_C8, HEX_CELL_D8, HEX_CELL_E8,
    HEX_CELL_F8, HEX_CELL_G8, HEX_CELL_H8, HEX_CELL_I8, HEX_CELL_J8,
    HEX_CELL_K8, HEX_CELL_L8, HEX_CELL_M8, HEX_CELL_N8, HEX_CELL_O8,
    HEX_CELL_P8, HEX_CELL_Q8, HEX_CELL_R8, HEX_CELL_S8,

    HEX_CELL_A9, HEX_CELL_B9, HEX_CELL_C9, HEX_CELL_D9, HEX_CELL_E9,
    HEX_CELL_F9, HEX_CELL_G9, HEX_CELL_H9, HEX_CELL_I9, HEX_CELL_J9,
    HEX_CELL_K9, HEX_CELL_L9, HEX_CELL_M9, HEX_CELL_N9, HEX_CELL_O9,
    HEX_CELL_P9, HEX_CELL_Q9, HEX_CELL_R9, HEX_CELL_S9,

    HEX_CELL_A10, HEX_CELL_B10, HEX_CELL_C10, HEX_CELL_D10, HEX_CELL_E10,
    HEX_CELL_F10, HEX_CELL_G10, HEX_CELL_H10, HEX_CELL_I10, HEX_CELL_J10,
    HEX_CELL_K10, HEX_CELL_L10, HEX_CELL_M10, HEX_CELL_N10, HEX_CELL_O10,
    HEX_CELL_P10, HEX_CELL_Q10, HEX_CELL_R10, HEX_CELL_S10,

    HEX_CELL_A11, HEX_CELL_B11, HEX_CELL_C11, HEX_CELL_D11, HEX_CELL_E11,
    HEX_CELL_F11, HEX_CELL_G11, HEX_CELL_H11, HEX_CELL_I11, HEX_CELL_J11,
    HEX_CELL_K11, HEX_CELL_L11, HEX_CELL_M11, HEX_CELL_N11, HEX_CELL_O11,
    HEX_CELL_P11, HEX_CELL_Q11, HEX_CELL_R11, HEX_CELL_S11,

    HEX_CELL_A12, HEX_CELL_B12, HEX_CELL_C12, HEX_CELL_D12, HEX_CELL_E12,
    HEX_CELL_F12, HEX_CELL_G12, HEX_CELL_H12, HEX_CELL_I12, HEX_CELL_J12,
    HEX_CELL_K12, HEX_CELL_L12, HEX_CELL_M12, HEX_CELL_N12, HEX_CELL_O12,
    HEX_CELL_P12, HEX_CELL_Q12, HEX_CELL_R12, HEX_CELL_S12,

    HEX_CELL_A13, HEX_CELL_B13, HEX_CELL_C13, HEX_CELL_D13, HEX_CELL_E13,
    HEX_CELL_F13, HEX_CELL_G13, HEX_CELL_H13, HEX_CELL_I13, HEX_CELL_J13,
    HEX_CELL_K13, HEX_CELL_L13, HEX_CELL_M13, HEX_CELL_N13, HEX_CELL_O13,
    HEX_CELL_P13, HEX_CELL_Q13, HEX_CELL_R13, HEX_CELL_S13,

    HEX_CELL_A14, HEX_CELL_B14, HEX_CELL_C14, HEX_CELL_D14, HEX_CELL_E14,
    HEX_CELL_F14, HEX_CELL_G14, HEX_CELL_H14, HEX_CELL_I14, HEX_CELL_J14,
    HEX_CELL_K14, HEX_CELL_L14, HEX_CELL_M14, HEX_CELL_N14, HEX_CELL_O14,
    HEX_CELL_P14, HEX_CELL_Q14, HEX_CELL_R14, HEX_CELL_S14,

    HEX_CELL_A15, HEX_CELL_B15, HEX_CELL_C15, HEX_CELL_D15, HEX_CELL_E15,
    HEX_CELL_F15, HEX_CELL_G15, HEX_CELL_H15, HEX_CELL_I15, HEX_CELL_J15,
    HEX_CELL_K15, HEX_CELL_L15, HEX_CELL_M15, HEX_CELL_N15, HEX_CELL_O15,
    HEX_CELL_P15, HEX_CELL_Q15, HEX_CELL_R15, HEX_CELL_S15,

    HEX_CELL_A16, HEX_CELL_B16, HEX_CELL_C16, HEX_CELL_D16, HEX_CELL_E16,
    HEX_CELL_F16, HEX_CELL_G16, HEX_CELL_H16, HEX_CELL_I16, HEX_CELL_J16,
    HEX_CELL_K16, HEX_CELL_L16, HEX_CELL_M16, HEX_CELL_N16, HEX_CELL_O16,
    HEX_CELL_P16, HEX_CELL_Q16, HEX_CELL_R16, HEX_CELL_S16,

    HEX_CELL_A17, HEX_CELL_B17, HEX_CELL_C17, HEX_CELL_D17, HEX_CELL_E17,
    HEX_CELL_F17, HEX_CELL_G17, HEX_CELL_H17, HEX_CELL_I17, HEX_CELL_J17,
    HEX_CELL_K17, HEX_CELL_L17, HEX_CELL_M17, HEX_CELL_N17, HEX_CELL_O17,
    HEX_CELL_P17, HEX_CELL_Q17, HEX_CELL_R17, HEX_CELL_S17,

    HEX_CELL_A18, HEX_CELL_B18, HEX_CELL_C18, HEX_CELL_D18, HEX_CELL_E18,
    HEX_CELL_F18, HEX_CELL_G18, HEX_CELL_H18, HEX_CELL_I18, HEX_CELL_J18,
    HEX_CELL_K18, HEX_CELL_L18, HEX_CELL_M18, HEX_CELL_N18, HEX_CELL_O18,
    HEX_CELL_P18, HEX_CELL_Q18, HEX_CELL_R18, HEX_CELL_S18,

    HEX_CELL_A19, HEX_CELL_B19, HEX_CELL_C19, HEX_CELL_D19, HEX_CELL_E19,
    HEX_CELL_F19, HEX_CELL_G19, HEX_CELL_H19, HEX_CELL_I19, HEX_CELL_J19,
    HEX_CELL_K19, HEX_CELL_L19, HEX_CELL_M19, HEX_CELL_N19, HEX_CELL_O19,
    HEX_CELL_P19, HEX_CELL_Q19, HEX_CELL_R19, HEX_CELL_S19,
    
    // @}
    
    /** The invalid HexPoint. */
    FIRST_INVALID

} HexPoint;

/** The value of the last interior cell. */
static const HexPoint LAST_CELL = HEX_CELL_S19;

//----------------------------------------------------------------------------

#endif
