#!/usr/bin/python -u
#----------------------------------------------------------------------------
# $Id: twogtp.py 1891 2009-02-02 01:24:37Z broderic $
#----------------------------------------------------------------------------

import fcntl, getopt, os, socket, string, sys, time

from random import randrange
from program import Program 
from game import Game
from gameplayer import GamePlayer

#----------------------------------------------------------------------------

class ResultsFile:
    def __init__(self, name, header):
        self._name = name
        self._wasExisting = self._checkExisting()
        if self._wasExisting:
            self._lastIndex = self._findLastIndex()
            self._printTimeStamp()
        else:
            self._lastIndex = -1;
            self._printHeader(header)
        
    def addResult(self, currentRound, opening, blackName, whiteName,
                  resultBlack, resultWhite, gameLen,
                  elapsedBlack, elapsedWhite,
                  error, errorMessage):

        opening = opening.replace('swap-pieces', 'sp')
        opening = opening.replace('swap-sides', 'ss')
        
#        if (len(opening) > 12):
#            opening = opening[0:13] + "..."
#        else:
#            opening = opening + " "*(15-len(opening))
        
        self._lastIndex += 1
        f = open(self._name, "a")
        f.write("%04i\t%i\t%s\t%s\t%s\t%s\t%s\t%i\t%.1f\t%.1f\t%s\t%s\n" \
                % (self._lastIndex, int(currentRound), opening,
                   blackName, whiteName, resultBlack, resultWhite,
                   gameLen, elapsedBlack, elapsedWhite,
                   error, errorMessage))
        f.close()

    def wasExisting():
        return _wasExisting

    def clear(self):
        f = open(self._name, "w")
        f.close()
        self._printHeader()
        self._gameIndex = -1;
        self._wasExisting = 0

    def getLastIndex(self):
        return self._lastIndex

    def _checkExisting(self):
        try:
            f = open(self._name, "r")
        except IOError:
            return 0
        f.close()
        return 1

    def _findLastIndex(self):
        f = open(self._name, "r")
        last = -1
        line = f.readline()
        while line != "":
            if line[0] != "#":
                array = string.split(line, "\t")
                last = int(array[0])
            line = f.readline()
        f.close()
        return last

    def _printHeader(self, infolines):
        f = open(self._name, "w")
        f.write("# Game results file generated by twogtp.py.\n" \
                "#\n")
        for l in infolines:
            f.write("# %s\n" % l);
        f.write("#\n" \
                "# GAME\tROUND\tOPENING\tBLACK\tWHITE\tRES_B\tRES_W\tLENGTH\tTIME_B\tTIME_W\tERR\tERR_MSG\n" \
                "#\n")
        f.close()
        self._printTimeStamp()

    def _printTimeStamp(self):
        f = open(self._name, "a")
        timeStamp = time.strftime("%Y-%m-%d %X %Z", time.localtime())
        f.write("# Date: " + timeStamp + "\n");
        f.close()

#----------------------------------------------------------------------------

class Tournament:
    def __init__(self,
                 p1name, p1cmd, p2name, p2cmd, size, rounds, outdir,
                 openingFile, verbose):

        self._p1name = p1name
        self._p1cmd = p1cmd
        self._p2name = p2name
        self._p2cmd = p2cmd
        self._size = size
        self._rounds = rounds
        self._outdir = outdir
        self._verbose = verbose
        
        info = ["p1name: " + p1name, \
                "p1cmd: " + p1cmd, \
                "p2name: " + p2name, \
                "p2cmd: " + p2cmd, \
                "Boardsize: " + `size`, \
                "Rounds: " + `rounds`, \
                "Openings: " + openingFile,  \
                "Directory: " + outdir, \
                "Start Date: "
                + time.strftime("%Y-%m-%d %X %Z", time.localtime())]
        
        if verbose:
            for line in info:
                print line
        self._resultsFile = ResultsFile(outdir + "/results", info)

        if (openingFile != ''):
            self._openings = []
            f = open(openingFile, 'r')
            lines = f.readlines()
            f.close()
            for line in lines:
                self._openings.append(string.strip(line))

    def playTourney(self):
        gamesPerRound = 2*len(self._openings);
        first = self._resultsFile.getLastIndex() + 1
        for i in range(first, self._rounds*gamesPerRound):
            currentRound = i / gamesPerRound;
            gameInRound = i % gamesPerRound;
            openingIndex = gameInRound / 2;
            
            opening = self._openings[openingIndex];
            
            if ((i % 2) == 0):
                self.playGame(i, currentRound,
                              self._p1name, self._p1cmd,
                              self._p2name, self._p2cmd,
                              opening, self._verbose)
            else:
                self.playGame(i, currentRound,
                              self._p2name, self._p2cmd,
                              self._p1name, self._p1cmd,
                              opening, self._verbose)

    def handleResult(self, swapped, result):
        ret = result
        if swapped:
            if (result[0:2] == 'B+'):
                ret = 'W+' + result[2:]
            elif (result[0:2] == 'W+'):
                ret = 'B+' + result[2:]
        return ret

    def playGame(self, gameIndex, currentRound, 
                 blackName, blackCmd, whiteName, whiteCmd,
                 opening, verbose):
        if verbose:
            print
            print "==========================================================="
            print "Game ", gameIndex
            print "==========================================================="
            
        bcmd = "nice " + blackCmd + \
               " --seed %SRAND" + \
               " --logfile-name " + self._outdir + "/" + blackName + ".log"
        wcmd = "nice " + whiteCmd + \
               " --seed %SRAND" + \
               " --logfile-name " + self._outdir + "/" + whiteName + ".log"
        
        black = Program("B", bcmd, verbose)
        white = Program("W", wcmd, verbose)
        
        resultBlack = "?"
        resultWhite = "?"
        error = 0
        errorMessage = ""
        game = Game()  # just a temporary
        gamePlayer = GamePlayer(black, white, self._size)
        try:
            game = gamePlayer.play(opening, verbose)
            swapped = game.playedSwap()
            resultBlack = self.handleResult(swapped, black.getResult())
            resultWhite = self.handleResult(swapped, white.getResult())
        except GamePlayer.Error:
            error = 1
            errorMessage = gamePlayer.getErrorMessage()
        except Program.Died:
            error = 1
            errorMessage = "program died"

        name = "%s/%04i" % (self._outdir, gameIndex)

        # save the result
        # recall it has been flipped if a swap move was played
        result = "?"
        if resultBlack == resultWhite:
            result = resultBlack
        game.setResult(result)

        # save it to the results file
        self._resultsFile.addResult(currentRound, opening,
                                    blackName, whiteName,
                                    resultBlack, resultWhite,
                                    # -1 so we don't count "resign" as a move
                                    game.getLength()-1,
                                    game.getElapsed("black"),
                                    game.getElapsed("white"),
                                    error, errorMessage)

        # save game
        gamePlayer.save(name + ".sgf", name, resultBlack, resultWhite)
        
        if error:
            print "Error: Game", gameIndex
            for p in (black, white):
                if p.isDead():
                    p.saveLog(name + ".log")
                    p.saveCommandLog(name + ".gtp")
                    break
        for program in [black, white]:
            try:
                program.sendCommand("quit");
            except Program.Died:
                pass
            
        return game

#----------------------------------------------------------------------------

def printUsage():
    sys.stderr.write(
        "Usage: twogtp.py [options]\n"
        "Options:\n"
        "  --dir      |-o: directory for output (default \"tourney\")\n"
        "  --force    |-f: overwrite old results (not implemented)\n"
        "  --help     |-h: print help\n"
        "  --openings |-l: openings to use\n"        
        "  --p1cmd    |-b: command of first program\n"
        "  --p1name   |  : name of first program\n"
        "  --p2cmd    |-w: command of second program\n"
        "  --p2name   |  : name of second program\n"
        "  --quiet    |-q: do not show log and board after each move\n"
        "  --rounds   |-r: number of rounds (default 1)\n"
        "  --size     |-s: boardsize (default 11)\n")

#----------------------------------------------------------------------------

def main():
    force = 0
    rounds = 1
    outdir = "tourney"
    size = 11
    verbose = True
    p1name = ""
    p1cmd = ""
    p2name = ""
    p2cmd = ""
    openings = ""
    
    try:
        options = "b:f:ho:s:w:ql:"
        longOptions = ["p1cmd=", "p1name=", "p2cmd=", "p2name=", \
                       "force", "rounds=", "help", "dir=", "size=", \
                       "quiet", "openings="]
        opts, args = getopt.getopt(sys.argv[1:], options, longOptions)
    except getopt.GetoptError:
        printUsage()
        sys.exit(-1)

    for o, v in opts:
        print "o = '" + o + "', v = '" + v + "'"
        if o in ("-b", "--p1cmd"):
            p1cmd = v
        elif o in ("--p1name"):
            p1name = v
        elif o in ("-w", "--p2cmd"):
            p2cmd = v
        elif o in ("--p2name"):
            p2name = v
        elif o in ("-f", "--force"):
            force = 1
        elif o in ("-r", "--rounds"):
            rounds = int(v)
        elif o in ("-h", "--help"):
            printUsage()
            sys.exit()
        elif o in ("-o", "--dir"):
            outdir = v
        elif o in ("-s", "--size"):
            size = int(v)
        elif o in ("-q", "--quiet"):
            verbose = False
        elif o in ("-l", "--openings"):
            openings = v

    if (p1cmd == "" or p2cmd == "" or p1name == "" or p2name == ""):
        printUsage()
        sys.exit()
    
#    if force:
#        resultsFile.clear()

#    if resultsFile.getLastIndex() + 1 >= games:
#        sys.stderr.write("Data file \"%s\" already contains >=%i games." \
#                         % (resultsFile.getName(), games))
#        return
            
           
    t = Tournament(p1name, p1cmd, p2name, p2cmd, size, rounds, \
                   outdir, openings, verbose)
    t.playTourney()

main()

#----------------------------------------------------------------------------
